services:
  php-fpm:
    build:
      context: ./docker/php-fpm
      args:
        USER_UID: ${USER_UID}
        USER_GID: ${USER_GID}
        TIMEZONE: ${TIMEZONE}
    container_name: php-fpm
    volumes:
      - ./app:/var/www
      - ./docker/php-fpm/logs/:/var/log
    networks:
      - symfony
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000" ]
      interval: 30s
      retries: 3
      start_period: 5s
      timeout: 10s

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./docker/nginx/logs/:/var/log/nginx
    depends_on:
      - php-fpm
    networks:
      - symfony

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.16.4
    container_name: elastic
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - cluster.routing.allocation.disk.threshold_enabled=true
      - cluster.routing.allocation.disk.watermark.low=5gb
      - cluster.routing.allocation.disk.watermark.high=3gb
      - cluster.routing.allocation.disk.watermark.flood_stage=2gb
    networks:
      - symfony

  kibana:
    image: docker.elastic.co/kibana/kibana:8.5.0
    container_name: kibana
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - symfony

networks:
  symfony:
    driver: bridge